steps:
  - id: 'get env from configmap'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: sh
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials $$CLOUDSDK_CONTAINER_CLUSTER --zone $$CLOUDSDK_COMPUTE_ZONE --project $PROJECT_ID
        kubectl get configmap "config-${_GKE_NAMESPACE}-${_GKE_DEPLOYMENT_NAME}" -n ${_GKE_NAMESPACE} -o go-template='{{range $k,$v := .data}}{{printf "%s=" $k}}{{if not $v}}{{$v}}{{else}}{{$v}}{{end}}{{"\n"}}{{end}}' > .env.temp
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1-a'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-testnet'

  - id: 'build image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}', '.']
    timeout: '1600s'

  - id: 'push image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}']

  - id: 'deploy revision with tag'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--platform',
        'managed',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
        '--image',
        'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}',
        '--tag',
        'pr-${_PR_NUMBER}',
      ]

  - id: 'link revision on pull request'
    name: 'gcr.io/${PROJECT_ID}/deployment-previews' # our custom builder
    secretEnv: ['GITHUB_TOKEN']
    args:
      [
        'set',
        '--project-id',
        '${PROJECT_ID}',
        '--region',
        '${_REGION}',
        '--service',
        '${_SERVICE_NAME}',
        '--pull-request',
        '${_PR_NUMBER}',
        '--repo-name',
        '${_GITHUB_REPO}',
        '--commit-sha',
        '${SHORT_SHA}',
      ]

timeout: 1600s

substitutions:
  _SERVICE_NAME: paras-landing
  _REGION: asia-southeast1
  _GITHUB_REPO: $(pull_request.pull_request.head.repo.full_name)

options:
  dynamicSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: 'GITHUB_TOKEN'
